# Generated by Django 5.2.6 on 2026-04-15 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CitizenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=180)),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=18)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ERPOperatorMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('erp_employee_id', models.PositiveIntegerField(unique=True)),
                ('erp_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=180)),
                ('employee_number', models.CharField(blank=True, max_length=40)),
                ('tax_id', models.CharField(blank=True, max_length=18)),
                ('secretariat_code', models.CharField(blank=True, max_length=20)),
                ('department_code', models.CharField(blank=True, max_length=20)),
                ('position_title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='active', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ERPSecretariatMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('erp_id', models.PositiveIntegerField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbound', 'Saída'), ('inbound', 'Entrada')], default='outbound', max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('success', models.BooleanField(default=False)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('target_path', models.CharField(max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=80)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CitizenProfileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(blank=True, max_length=180)),
                ('mother_name', models.CharField(blank=True, max_length=160)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, default='Amargosa', max_length=120)),
                ('erp_citizen_id', models.CharField(blank=True, max_length=80)),
                ('external_reference', models.CharField(blank=True, max_length=80)),
                ('sync_status', models.CharField(default='local', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_extension', to='triagem.citizenrecord')),
            ],
            options={
                'verbose_name': 'Extensão do cidadão',
                'verbose_name_plural': 'Extensões do cidadão',
            },
        ),
        migrations.CreateModel(
            name='ERPDepartmentMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('erp_id', models.PositiveIntegerField(unique=True)),
                ('secretariat_code', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('secretariat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='triagem.erpsecretariatmirror')),
            ],
            options={
                'ordering': ['secretariat__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('requires_screening', models.BooleanField(default=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='triagem.attendanceunit')),
            ],
            options={
                'ordering': ['unit__name', 'name'],
                'unique_together': {('unit', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=20)),
                ('issued_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('daily_sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('issued', 'Emitida'), ('screening', 'Em triagem'), ('waiting', 'Aguardando'), ('called', 'Chamada'), ('in_service', 'Em atendimento'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='issued', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('waiting_started_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='triagem.citizenrecord')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='triagem.attendanceunit')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='triagem.servicecatalog')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['unit', 'status', 'issued_on', 'issued_at'], name='triagem_que_unit_id_efda5d_idx'), models.Index(fields=['ticket_number'], name='triagem_que_ticket__c0809b_idx')],
                'constraints': [models.UniqueConstraint(fields=('unit', 'issued_on', 'daily_sequence'), name='uq_queue_ticket_unit_day_sequence'), models.UniqueConstraint(fields=('unit', 'issued_on', 'ticket_number'), name='uq_queue_ticket_unit_day_number')],
            },
        ),
    ]
