# Generated by Django 5.2.6 on 2026-04-15 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#9f1239', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('target_wait_minutes', models.PositiveIntegerField(default=15)),
                ('is_preferential', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen_name', models.CharField(blank=True, max_length=180)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('checked_in', 'Recepcionado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='triagem.citizenrecord')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='triagem.servicecatalog')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='triagem.attendanceunit')),
                ('priority_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='triagem.priorityprofile')),
            ],
            options={
                'ordering': ['scheduled_for', 'created_at'],
                'indexes': [models.Index(fields=['unit', 'status', 'scheduled_for'], name='triagem_app_unit_id_98f793_idx')],
            },
        ),
    ]
